name = "NQCDistributions"
uuid = "657014a1-bd25-4aa2-92cb-cbcede0310ad"
authors = ["James Gardner <james.gardner1421@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RingPolymerArrays = "81cd853e-d334-476c-b156-f95acc8a32dc"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
